# Generated by Django 3.1.5 on 2021-01-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated',
        ),
    ]
