django:
  build: .
  volumes:
    - .:/app
migration:
  extends:
    service: django
  command: python manage.py migrate
server:
  extends:
    service: django
  command: python manage.py runserver 0.0.0.0:5000
  ports:
    - "5000:5000"