# Generated by Django 3.1.5 on 2021-01-31 14:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0003_csv_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(default=django.utils.timezone.now, help_text='Допускаются только файлы формата .csv', upload_to='csvs', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
            preserve_default=False,
        ),
    ]
